### ISSUE TITLE
ModuleNotFoundError: No module named 'models.model_multi_task'

### ISSUE THREAD

**Issue by dmharoon** [cvignac/SMP#2]
Hi, 
Thanks for the code!
It seems the model definitions folder is missing i.e. model_cycles, model_multi_task, model_zinc. Can you please update? Thanks.

**Comment by cvignac** [comment]
Thank you for noticing, for some reason I had put models/ in the .gitignore file. It's now updated.

**Comment by dmharoon** [comment]
Thanks!
